### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by FransUrbo** [stripe/datadog-checks#61]
I'm trying to get this check working on Ubuntu 16.04LTS with DataDog v1:5.14.1-1, OpenLDAP v2.4.42+dfsg-2ubuntu3.2.

I can search the `cn=Monitor` backend just fine:

```
turbo@admin:~$ ldapsearch -ZZ -x -LLL -H ldap://localhost -b 'cn=monitor' dn | grep ^dn: | wc -l
72
```

The slapd.yaml:
```
init_config:
instances:
  - uri: ldap://localhost
    network_timeout: 10              # Timeout for connections
    protocol_version: 3              # Protocol version (2 or 3)
    starttls: true                   # Use STARTTLS (default: false)
```

but all I get is:
```
turbo@admin:~$ sudo dd-agent info
2017-06-21 11:20:06,032 | ERROR | dd.collector | collector(dd-agent:604) | Uncaught error running the Agent
Traceback (most recent call last):
  File "/usr/bin/dd-agent", line 600, in <module>
    sys.exit(main())
  File "/usr/bin/dd-agent", line 526, in main
    return Agent.info(verbose=options.verbose)
  File "/usr/bin/dd-agent", line 218, in info
    return CollectorStatus.print_latest_status(verbose=verbose)
  File "/opt/datadog-agent/agent/checks/check_status.py", line 282, in print_latest_status
    message = module_status.render()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 180, in render
    ] + ["", ""]
  File "/opt/datadog-agent/agent/checks/check_status.py", line 546, in body_lines
    '  ' + '-' * (len(cs.name) + 3 + len(cs.check_version))
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/bin/dd-agent", line 600, in <module>
    sys.exit(main())
  File "/usr/bin/dd-agent", line 526, in main
    return Agent.info(verbose=options.verbose)
  File "/usr/bin/dd-agent", line 218, in info
    return CollectorStatus.print_latest_status(verbose=verbose)
  File "/opt/datadog-agent/agent/checks/check_status.py", line 282, in print_latest_status
    message = module_status.render()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 180, in render
    ] + ["", ""]
  File "/opt/datadog-agent/agent/checks/check_status.py", line 546, in body_lines
    '  ' + '-' * (len(cs.name) + 3 + len(cs.check_version))
TypeError: object of type 'NoneType' has no len()
```

Running the check on its on doesn't produce any error (previously, it was missing a whole bunch of python packages, which you might want to update the documentation with):
```
turbo@admin:~$ python /etc/dd-agent/checks.d/slapd.py
turbo@admin:~$ echo $?
0
```

The packages I was missing on my bog-standard Ubuntu was:
python-ldap, python-yaml, python-ntplib, python-requests, python-simplejson, python-docker, python-etcd, python-pip, python-kazoo
And with pip installed, I could install the python-consul package (which wasn't available through apt).

**Comment by FransUrbo** [comment]
Reading up on checks for DD, I see:

```
turbo@admin:~$ sudo dd-agent check slapd
2017-06-21 11:31:59,973 | ERROR | dd.collector | config(config.py:834) | Unable to import check module slapd.py from checks.d
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 830, in _get_check_class
    check_module = imp.load_source('checksd_%s' % check_name, check_path)
  File "/etc/dd-agent/checks.d/slapd.py", line 10, in <module>
    import ldap
ImportError: No module named ldap
2017-06-21 11:31:59,978 | INFO | dd.collector | config(config.py:1140) | initialized checks.d checks: ['ntp', 'disk', 'network']
```

This despite me installing both the `python-ldap`, `python-ldap3` and `python3-ldap3` packages.

**Comment by FransUrbo** [comment]
Hack to get this working was to add the following two lines at the very top of the `slapd.py` file:
```
import sys
sys.path.append('/usr/lib/python2.7/dist-packages')
```
